#!/bin/bash

function usage {
  echo "Usage: loop --cluster test"
  exit 1
}

while [ $# -gt 0 ]; do
  case $1 in
      --cluster) shift; cluster="$1"; shift;;
      *) usage;;
  esac
done

if [ -z "${cluster}" ]; then
  usage
fi

find services -type f \
  | cut -d"/" -f 2 \
  | xargs -I{} -P 5 -n1 ./deploy --cluster ${cluster} --service {}
