#!/bin/bash

function usage {
  echo "Usage: stop --cluster test"
  exit 1
}

while [ $# -gt 0 ]; do
  case $1 in
      --cluster) shift; cluster="$1"; shift;;
      *) usage;;
  esac
done

if [ -z "${cluster}" ]; then
  usage
fi

mkdir -p tmp

services=$(find services -type f | cut -d"/" -f 2)
echo "$services" | while read service; do
  echo [${service}] stopping
  aws ecs update-service --cluster ${cluster} --service ${service} --desired-count 0 > tmp/aws-service-${service}-stop.json
  echo [${service}] stopped
done

echo Done
