#!/bin/bash

eval "$(./docopts -h - : "$@" <<EOF
Usage: stop --cluster=<name>
EOF)"

mkdir -p tmp

services=$(find services -type f | cut -d"/" -f 2)
echo "$services" | while read service; do
  echo [${service}] stopping
  aws ecs update-service --cluster ${cluster} --service ${service} --desired-count 0 > tmp/aws-service-${service}-stop.json
  echo [${service}] stopped
done

echo Done
